### ISSUE TITLE
About domain overlapping

### ISSUE THREAD

**Issue by Monstarrr** [awslabs/pptod#15]
Hi! I am really interested in your work.
Anyway, I just found that in your preprocessing script there is nothing about removing the overlapping data between pretrain and finetuning. Will these overlapping domains affect the result of low-resource experiment?
Looking forward to your reply!

**Comment by yxuansu** [comment]
Hi @Monstarrr,

Thank you for your interest in our work.

During pre-training, we use different datasets except for the ones (i.e. MultiWOZ 2.0 and 2.1) that we are testing on. 
(1) We assume that, in the pre-training corpus, there is no data that is exactly the same as the data from MultiWOZ.
(2) In addition, our underlying assumption is that the pre-training corpus is, to some extent, similar to the end tasks in terms of data distribution. Therefore, we can acquire a model that possesses good generalization ability.

Please let me know if you have further questions :-)
