### ISSUE TITLE
DST inference result on MultiWOZ 2.1

### ISSUE THREAD

**Issue by SuvodipDey** [awslabs/pptod#3]
Hi,
Firstly, congratulation on this nice work. 
Could you please upload the DST inference result on the MultiWOZ 2.1 dataset as well. Alternatively, please let me know how to generate the same on the MultiWOZ 2.1.

**Comment by yxuansu** [comment]
Hi,
Thank you for your question! Due to copy right issue, we were not able to redistribute MultiWOZ 2.1. For processing the data, you could refer details in this repo https://github.com/TonyNemo/UBAR-MultiWOZ. Feel free to contact me if you have further questions. :)

**Comment by SuvodipDey** [comment]
Okay. Thanks.
