### ISSUE TITLE
Plug-and-Play vs Cascaded Generation

### ISSUE THREAD

**Issue by zqwerty** [awslabs/pptod#4]
Hi, I have some questions about two E2E generation modes "Plug-and-Play vs Cascaded Generation":
1. In Plug-and-Play, how do you insert the DB results?
2. If the output of POL and NLG are generated in parallel, then what is the use of POL output? I've observed inconsistent between generated dialog acts and the response in https://raw.githubusercontent.com/awslabs/pptod/main/E2E_TOD/inference_result/small/full_training/inference_result_e2e_evaluation_inform_87.8_success_75.3_bleu_19.89_combine_score_101.44.json
3. In Cascaded Generation, how do you insert DB result & pol output?

Thanks!

**Comment by yxuansu** [comment]
> Hi, I have some questions about two E2E generation modes "Plug-and-Play vs Cascaded Generation":
> 
> 1. In Plug-and-Play, how do you insert the DB results?
> 2. If the output of POL and NLG are generated in parallel, then what is the use of POL output? I've observed inconsistent between generated dialog acts and the response in https://raw.githubusercontent.com/awslabs/pptod/main/E2E_TOD/inference_result/small/full_training/inference_result_e2e_evaluation_inform_87.8_success_75.3_bleu_19.89_combine_score_101.44.json
> 3. In Cascaded Generation, how do you insert DB result & pol output?
> 
> Thanks!

Hey,

Thank you for your interest in our paper!

1. In the plug-and-play formulation, the pipeline is: (1) (DST-prompt, context) -> DST result and then we retrieve DB result; (2) (POL-prompt, context, DB result) -> POL result; and (3) (NLG-prompt, context, DB result) -> NLG result. Here, the item in () denotes the model input and the item following -> is the model output. As seen, steps (2) and (3) are completely decoupled. Furthermore, if we disregard the DB result in the generation pipeline, these three tasks (DST, POL, and NLG) can be solved in a fully paralleled way (as shown in the last two rows in Table 6 of the paper). 

2. As described previously, the POL and NLG are generated in a decoupled way. So the POL result is just generated following a conventional practice. It is natural that there are some inconsistencies in the generated POL and NLG results as they are generated in a decoupled way. However, in many cases, we see that this decoupled nature helps the model to alleviate the error accumulation between different tasks. For example, in some cases, the model might generate a wrong POL result but generate a correct NLG result. 

3. In the cascaded generation formulation, we use the conventional pipeline as adopted in the previous studies (e.g., SimpleTOD and SOLOIST). Concretely, the pipeline is: (1) (context)->DST result and then retrieve DB result; (2) (context, DST result, DB result) -> POL result;  and (3) (context, DST result, DB result, POL result) -> NLG result. As seen, these three steps have to be solved in a sequential way as the latter subtasks depend on previous ones. And this formulation suffers much higher inference latency, as shown in Table 6 of our paper.

I hope my response could help you!

Best,

Yixuan

**Comment by zqwerty** [comment]
Thanks. So in Plug-and-Play, the E2E model does not need the POL output because the NLG output is enough?

**Comment by yxuansu** [comment]
> Thanks. So in Plug-and-Play, the E2E model does not need the POL output because the NLG output is enough?

Yeah, you are correct. Only the DST and NLG results should be enough for evaluation.

**Comment by zqwerty** [comment]
Sorry. Why the E2E results of `Table 6 last row` and `Table 8 first row` are different? I think both are T5-small without dialogue multi-task pre-training on MultiWOZ 2.0

**Comment by yxuansu** [comment]
> Sorry. Why the E2E results of `Table 6 last row` and `Table 8 first row` are different? I think both are T5-small without dialogue multi-task pre-training on MultiWOZ 2.0

They should be results from different runs. We will double check the numbers and make them consistent in the next version.
