### ISSUE TITLE
How to lexicalize the generated responses?

### ISSUE THREAD

**Issue by xiami2019** [awslabs/pptod#5]
Hi! Do you have tried to lexicalize the response with real tokens in stead of place holders?

**Comment by yxuansu** [comment]
> Hi! Do you have tried to lexicalize the response with real tokens in stead of place holders?

Hi, thank you for your interest in our paper! We did try to lexicalize the response and we provide an example in the appendix of our [paper](https://arxiv.org/pdf/2109.14739.pdf) (Table 11). If you want to lexicalize the response by yourself, you can refer to the details in this [file](https://github.com/awslabs/pptod/blob/main/E2E_TOD/db_ops.py). It should be able to help you :)
