### ISSUE TITLE
Performance impact of `shuffle_mode`?

### ISSUE THREAD

**Issue by kingb12** [awslabs/pptod#7]
Hi all, really enjoyed this approach and am exploring the data setup in the repository. I noticed you support two shuffle modes between epochs, one by turn (complete shuffle) and one which preserves sessions and their turn order. Is there any particular advantage to the session_level shuffle mode or vice-versa?

**Comment by yxuansu** [comment]
> Hi all, really enjoyed this approach and am exploring the data setup in the repository. I noticed you support two shuffle modes between epochs, one by turn (complete shuffle) and one which preserves sessions and their turn order. Is there any particular advantage to the session_level shuffle mode or vice-versa?

Hi,

Thank you for your interest in our work. Actually, these two modes perform quite the same. The shuffle session_level might perform slightly better but the difference is not significant.

**Comment by kingb12** [comment]
Thank you!
